export default {
  topic: 'liandongzhihui',
  legendCtrl: 'liandongzhihui',
  commonLayers: [],
  defaultView: {
    sceneName: 'KNY',
  },
  cardNames: {
    liandongzhihui: {
      cardShowLegends: [
        'Camera',
        'Event Point',
        'Risks Points',
        'Protection Target',
        'Alarm Event',
        'Shelter',
        'Security Circle',
        'Emergency Material',
        'Expert Team',
        'Fire Truck',
        'Ambulance',
        'Transport Vehicle',
        'Police',
        'Firefighter',
        'Medical Personnel',
      ],
      cardShowLayers: ['DengganIcon'],
    },
  },
  allLayers: {
    Camera: [
      {
        id: 'ScatterPoint-CameraGA',
        layerType: 'LandmarkMap',
        scatterType: 'Camera',
        isClick: true,
        coordZ: 0,
        jsonPath: './data/GongGongAnQuan/Camera.json',
        legend: {
          name: 'Camera',
          color: '#ffff',
          iconName: 'custom-Camera',
        },
      },
    ],
    DengganIcon: [
      {
        id: 'Model-DengganIcon',
        layerType: 'Model',
        scatterType: 'DengganIcon',
        isClick: true,
        coordZ: 0,
        jsonPath: './data/ZhiHuiDengGan/SmartPoleSites.json',
        legend: {
          name: 'DengganIcon',
          color: '#ffff',
          iconName: 'custom-dengganIcon',
        },
      },
    ],
    'Event Point': [
      {
        id: 'liandongzhihui-EventPoint',
        layerType: 'LandmarkMap',
        scatterType: 'Event Point',
        isClick: true,
        coordZ: 0,
        jsonPath: './data/LianDongZhiHui/EventPoint.json',
        legend: {
          name: 'EventPoint',
          color: '#ffff',
          iconName: 'custom-EventPoint',
        },
      },
    ],
    'Risks Points': [
      {
        id: 'liandongzhihui-RisksPoints',
        layerType: 'LandmarkMap',
        scatterType: 'Risks Points',
        isClick: true,
        coordZ: 0,
        jsonPath: './data/LianDongZhiHui/RisksPoints.json',
        legend: {
          name: 'RisksPoints',
          color: '#ffff',
          iconName: 'custom-RisksPoints',
        },
      },
    ],
    'Protection Target': [
      {
        id: 'liandongzhihui-ProtectionTarget',
        layerType: 'LandmarkMap',
        scatterType: 'Protection Target',
        isClick: true,
        coordZ: 0,
        jsonPath: './data/LianDongZhiHui/ProtectionTarget.json',
        legend: {
          name: 'ProtectionTarget',
          color: '#ffff',
          iconName: 'custom-ProtectionTarget',
        },
      },
    ],
    'Alarm Event': [
      {
        id: 'liandongzhihui-AlarmEvent',
        layerType: 'LandmarkMap',
        scatterType: 'Alarm Event',
        isClick: true,
        coordZ: 0,
        jsonPath: './data/LianDongZhiHui/AlarmEvent.json',
        legend: {
          name: 'AlarmEvent',
          color: '#ffff',
          iconName: 'custom-AlarmEvent',
        },
      },
    ],
    Shelter: [
      {
        id: 'ScatterPoint-Shelter',
        layerType: 'LandmarkMap',
        scatterType: 'Shelter',
        isClick: true,
        coordZ: 0,
        jsonPath: './data/GongGongAnQuan/Shelter.json',
        legend: {
          name: 'Shelter',
          color: '#ffff',
          iconName: 'custom-Shelter',
        },
      },
    ],
    'Security Circle': [
      {
        id: 'liandongzhihui-SecurityCircle',
        layerType: 'LandmarkMap',
        scatterType: 'Security Circle',
        isClick: true,
        coordZ: 0,
        jsonPath: './data/LianDongZhiHui/SecurityCircle.json',
        legend: {
          name: 'SecurityCircle',
          color: '#ffff',
          iconName: 'custom-SecurityCircle',
        },
      },
    ],
    'Emergency Material': [
      {
        id: 'liandongzhihui-EmergencyMaterial',
        layerType: 'LandmarkMap',
        scatterType: 'Emergency Material',
        isClick: true,
        coordZ: 0,
        jsonPath: './data/LianDongZhiHui/EmergencyMaterial.json',
        legend: {
          name: 'EmergencyMaterial',
          color: '#ffff',
          iconName: 'custom-EmergencyMaterial',
        },
      },
    ],
    'Expert Team': [
      {
        id: 'liandongzhihui-ExpertTeam',
        name: 'ExpertTeam',
        coordType: 0,
        coordTypeZ: 0,
        trackStyle: 'style001',
        trackDuration: 10,
        iconRotate: 'disable',
        objLife: 60 * 60 * 24,
        trackWidth: 10,
        duration: 1,
        visible: true,
        layerType: 'Trajectories',
        scatterType: 'Expert Team',
        isClick: true,
        coordZ: -4.9899990845,
        jsonPath: './data/LianDongZhiHui/ExpertTeamone.json',
        legend: {
          name: 'ExpertTeam',
          iconName: 'custom-ExpertTeam',
          iconScale: 1,
          labelScale: 1,
          trackColor: '#ff0000',
        },
      },
    ],

    'Fire Truck': [
      {
        id: 'liandongzhihui-FireTruck',
        name: 'FireTruck',
        coordType: 0,
        coordTypeZ: 0,
        trackStyle: 'style001',
        trackDuration: 10,
        iconRotate: 'disable',
        objLife: 60 * 60 * 24,
        trackWidth: 10,
        duration: 1,
        visible: true,
        layerType: 'Trajectories',
        scatterType: 'Fire Truck',
        isClick: true,
        coordZ: -4.9899990845,
        jsonPath: './data/LianDongZhiHui/FireTruck.json',
        legend: {
          name: 'FireTruck',
          iconName: 'custom-FireTruck',
          iconScale: 1,
          labelScale: 1,
          trackColor: '#ff0000',
        },
      },
    ],
    Ambulance: [
      {
        id: 'liandongzhihui-Ambulance',
        name: 'Ambulance',
        coordType: 0,
        coordTypeZ: 0,
        trackStyle: 'style001',
        trackDuration: 10,
        iconRotate: 'disable',
        objLife: 60 * 60 * 24,
        trackWidth: 10,
        duration: 1,
        visible: true,
        layerType: 'Trajectories',
        scatterType: 'Ambulance',
        isClick: true,
        coordZ: -4.9899990845,
        jsonPath: './data/LianDongZhiHui/Ambulance.json',
        legend: {
          name: 'Ambulance',
          iconName: 'custom-Ambulance',
          iconScale: 1,
          labelScale: 1,
          trackColor: '#ff0000',
        },
      },
    ],
    'Transport Vehicle': [
      {
        id: 'liandongzhihui-TransportVehicle',
        name: 'TransportVehicle',
        coordType: 0,
        coordTypeZ: 0,
        trackStyle: 'style001',
        trackDuration: 10,
        iconRotate: 'disable',
        objLife: 60 * 60 * 24,
        trackWidth: 10,
        duration: 1,
        visible: true,
        layerType: 'Trajectories',
        scatterType: 'Transport Vehicle',
        isClick: true,
        coordZ: -4.9899990845,
        jsonPath: './data/LianDongZhiHui/TransportVehicle.json',
        legend: {
          name: 'TransportVehicle',
          iconName: 'custom-TransportVehicle',
          iconScale: 1,
          labelScale: 1,
          trackColor: '#ff0000',
        },
      },
    ],
    Police: [
      {
        id: 'liandongzhihui-Police',
        name: 'Police',
        coordType: 0,
        coordTypeZ: 0,
        trackStyle: 'style001',
        trackDuration: 10,
        iconRotate: 'disable',
        objLife: 60 * 60 * 24,
        trackWidth: 10,
        duration: 1,
        visible: true,
        layerType: 'Trajectories',
        scatterType: 'Police',
        isClick: true,
        coordZ: -4.9899990845,
        jsonPath: './data/LianDongZhiHui/Police.json',
        legend: {
          name: 'Police',
          iconName: 'custom-Police',
          iconScale: 1,
          labelScale: 1,
          trackColor: '#ff0000',
        },
      },
    ],
    Firefighter: [
      {
        id: 'liandongzhihui-Firefighter',
        name: 'Firefighter',
        coordType: 0,
        coordTypeZ: 0,
        trackStyle: 'style001',
        trackDuration: 10,
        iconRotate: 'disable',
        objLife: 60 * 60 * 24,
        trackWidth: 10,
        duration: 1,
        visible: true,
        layerType: 'Trajectories',
        scatterType: 'Firefighter',
        isClick: true,
        coordZ: -4.9899990845,
        jsonPath: './data/LianDongZhiHui/Firefighter.json',
        legend: {
          name: 'Firefighter',
          iconName: 'custom-Firefighter',
          iconScale: 1,
          labelScale: 1,
          trackColor: '#ff0000',
        },
      },
    ],
    'Medical Personnel': [
      {
        id: 'liandongzhihui-MedicalPersonnel',
        name: 'MedicalPersonnel',
        coordType: 0,
        coordTypeZ: 0,
        trackStyle: 'style001',
        trackDuration: 10,
        iconRotate: 'disable',
        objLife: 60 * 60 * 24,
        trackWidth: 10,
        duration: 1,
        visible: true,
        layerType: 'Trajectories',
        scatterType: 'Medical Personnel',
        isClick: true,
        coordZ: -4.9899990845,
        jsonPath: './data/LianDongZhiHui/MedicalPersonnel.json',
        legend: {
          name: 'MedicalPersonnel',
          iconName: 'custom-MedicalPersonnel',
          iconScale: 1,
          labelScale: 1,
          trackColor: '#ff0000',
        },
      },
    ],
  },
}
