export default {
  //Each map and key value in legendCtrls is consistent with the legendCtrl configured in layerConfig, where value is the legend array [the legend name is the same as the individual name in allLegends]
  legendCtrls: new Map([
    [
      'zhihuidenggan',
      [
        'Smart Lamp Pole/lamp',
        'Device Alarm',
        'Camera',
        'Advertisement Displa',
        'Smart Light Pole Weather Sensor',
        'Konza data center',
      ],
    ],
    [
      'gonggonganquan',
      [
        'Shelter',
        'Enterprise',
        'Camera',
        'Smart Light Pole Weather Sensor',
        'Key Project',
        'Security Incident',
        'Police Situation',
      ],
    ],
    [
      'zhaoshangyunxing',
      [
        'Leased Place Locations',
        'Key Project',
        'Enterprise',
        'Camera',
        'Alarm',
        'Pilot community',
        'weather sensor',
      ],
    ],
    [
      'jiaotongyunxing',
      ['Parking Lot', 'Camera', 'Checkpoint', 'Traffic Incident'],
    ],
    ['ChengShiGuiHua', ['Advertisement Displa']],
    [
      'QuYuQuanJing',
      [
        'Shelter',
        'Enterprise',
        'Camera',
        'Smart Light Pole Weather Sensor',
        'Key Project',
        'Security Incident',
        'Police Situation',
      ],
    ],
    ['ChengShiZhiLi', ['Smart Light Pole Weather Sensor']],
    [
      'ZhiHuiGuanLang',
      ['Parking Lot', 'Camera', 'Advertisement Displa', 'Security Incident'],
    ],
    [
      'shujuzhongxin',
      [
        'Camera',
        'Device Alarm',
        'Air Conditioner',
        'FusionModule',
        'Temperature Sensor',
        'Humidity Sensor',
      ],
    ],
    [
      'liandongzhihui',
      [
        'Camera',
        'Event Point',
        'Risks Points',
        'Protection Target',
        'Alarm Event',
        'Shelter',
        'Security Circle',
        'Emergency Material',
        'Expert Team',
        'Fire Truck',
        'Ambulance',
        'Transport Vehicle',
        'Police',
        'Firefighter',
        'Medical Personnel',
      ],
    ],
    [
      'ChengShiQuanJing',
      [
        'Camera Location',
        'Public Security Police Situation Point',
        'Alarm Event Point',
        'Historical Event Point',
        'Enterprise Location',
      ],
    ],
    [
      'MingShengFuWu',
      [
        'Hospital',
        'School',
        'Nursing Home',
        'Police Station',
        'Government Agency',
      ],
    ],
  ]),

  allLegends: [
    // zhihuidenggan
    {
      name: 'Konza data center',
      showName: 'Konza data center',
      imgUrl: '/img/legend/dataCenter.png',
      highlight: false,
    },
    {
      name: 'Smart Lamp Pole/lamp',
      showName: 'Smart Lamp Pole/lamp',
      imgUrl: '/img/legend/SmartLamp.png',
      highlight: false,
    },
    {
      name: 'Device Alarm',
      showName: 'Device Alarm',
      imgUrl: '/img/legend/DeviceAlarm.png',
      highlight: false,
    },
    {
      name: 'Camera',
      showName: 'Camera',
      imgUrl: '/img/legend/Camera.png',
      highlight: false,
    },
    {
      name: 'Advertisement Displa',
      showName: 'Advertisement Displa',
      imgUrl: '/img/legend/Advertisement.png',
      highlight: false,
    },
    {
      name: 'Smart Light Pole Weather Sensor',
      showName: 'Smart Light Pole Weather Sensor',
      imgUrl: '/img/legend/WeatherSensor.png',
      highlight: false,
    },
    {
      name: 'Shelter',
      showName: 'Shelter',
      imgUrl: '/img/legend/Shelter.png',
      highlight: false,
    },
    {
      name: 'Enterprise',
      showName: 'Enterprise',
      imgUrl: '/img/legend/Enterprise.png',
      highlight: false,
    },
    {
      name: 'Key Project',
      showName: 'Key Project',
      imgUrl: '/img/legend/KeyProject.png',
      highlight: false,
    },
    {
      name: 'Safety Production Accident',
      showName: 'Safety Production Accident',
      imgUrl: '/img/legend/SafetyProduction.png',
      highlight: false,
    },
    {
      name: 'Police Situation',
      showName: 'Police Situation',
      imgUrl: '/img/legend/PoliceSituation.png',
      highlight: false,
    },
    {
      name: 'Alarm',
      showName: 'Alarm',
      imgUrl: '/img/legend/Alarm.png',
      highlight: false,
    },
    {
      name: 'Pilot community',
      showName: 'Pilot community',
      imgUrl: '/img/legend/Pilot.png',
      highlight: false,
    },
    {
      name: 'weather sensor',
      showName: 'weather sensor',
      imgUrl: '/img/legend/weather.png',
      highlight: false,
    },
    {
      name: 'Leased Place Locations',
      showName: 'Leased Place Locations',
      imgUrl: '/img/legend/LeasedPlace.png',
      highlight: false,
    },
    {
      name: 'Leased Place Locations',
      showName: 'Leased Place Locations',
      imgUrl: '/img/legend/LeasedPlace.png',
      highlight: false,
    },
    {
      name: 'Leased Place Locations',
      showName: 'Leased Place Locations',
      imgUrl: '/img/legend/LeasedPlace.png',
      highlight: false,
    },
    {
      name: 'Parking Lot',
      showName: 'Parking Lot',
      imgUrl: '/img/legend/ParkingLot.png',
      highlight: false,
    },
    {
      name: 'Checkpoint',
      showName: 'Checkpoint',
      imgUrl: '/img/legend/Checkpoint.png',
      highlight: false,
    },
    {
      name: 'Traffic Incident',
      showName: 'Traffic Incident',
      imgUrl: '/img/legend/TrafficIncident.png',
      highlight: false,
    },
    {
      name: 'Security Incident',
      showName: 'Security Incident',
      imgUrl: '/img/legend/SecurityIncident.png',
      highlight: false,
    },
    {
      name: 'Air Conditioner',
      showName: 'Air Conditioner',
      imgUrl: '/img/legend/AirConditioner.png',
      highlight: false,
    },
    {
      name: 'FusionModule',
      showName: 'FusionModule',
      imgUrl: '/img/legend/FusionModule.png',
      highlight: false,
    },
    {
      name: 'Humidity Sensor',
      showName: 'Humidity Sensor',
      imgUrl: '/img/legend/HumiditySensor.png',
      highlight: false,
    },
    {
      name: 'Temperature Sensor',
      showName: 'Temperature Sensor',
      imgUrl: '/img/legend/TemperatureSensor.png',
      highlight: false,
    },
    {
      name: 'Event Point',
      showName: 'Event Point',
      imgUrl: '/img/legend/EventPoint.png',
      highlight: false,
    },
    {
      name: 'Risks Points',
      showName: 'Risks Points',
      imgUrl: '/img/legend/RisksPoints.png',
      highlight: false,
    },
    {
      name: 'Protection Target',
      showName: 'Protection Target',
      imgUrl: '/img/legend/ProtectionTarget.png',
      highlight: false,
    },
    {
      name: 'Alarm Event',
      showName: 'Alarm Event',
      imgUrl: '/img/legend/AlarmEvent.png',
      highlight: false,
    },
    {
      name: 'Security Circle',
      showName: 'Security Circle',
      imgUrl: '/img/legend/SecurityCircle.png',
      highlight: false,
    },
    {
      name: 'Emergency Material',
      showName: 'Emergency Material',
      imgUrl: '/img/legend/EmergencyMaterial.png',
      highlight: false,
    },
    {
      name: 'Expert Team',
      showName: 'Expert Team',
      imgUrl: '/img/legend/ExpertTeam.png',
      highlight: false,
      width: '20px',
      height: '37px',
    },
    {
      name: 'Fire Truck',
      showName: 'Fire Truck',
      imgUrl: '/img/legend/FireTruck.png',
      highlight: false,
      width: '20px',
      height: '37px',
    },
    {
      name: 'Ambulance',
      showName: 'Ambulance',
      imgUrl: '/img/legend/Ambulance.png',
      highlight: false,
      width: '20px',
      height: '37px',
    },
    {
      name: 'Transport Vehicle',
      showName: 'Transport Vehicle',
      imgUrl: '/img/legend/TransportVehicle.png',
      highlight: false,
      width: '20px',
      height: '37px',
    },
    {
      name: 'Police',
      showName: 'Police',
      imgUrl: '/img/legend/Police.png',
      highlight: false,
      width: '20px',
      height: '37px',
    },
    {
      name: 'Firefighter',
      showName: 'Firefighter',
      imgUrl: '/img/legend/Firefighter.png',
      highlight: false,
      width: '20px',
      height: '37px',
    },
    {
      name: 'Medical Personnel',
      showName: 'Medical Personnel',
      imgUrl: '/img/legend/MedicalPersonnel.png',
      highlight: false,
      width: '20px',
      height: '37px',
    },
    {
      name: 'Hospital',
      showName: 'Hospital',
      imgUrl: '/img/legend/Hospital.png',
      highlight: false,
    },
    {
      name: 'School',
      showName: 'School',
      imgUrl: '/img/legend/School.png',
      highlight: false,
    },
    {
      name: 'Nursing Home',
      showName: 'Nursing Home',
      imgUrl: '/img/legend/NursingHome.png',
      highlight: false,
    },
    {
      name: 'Police Station',
      showName: 'Police Station',
      imgUrl: '/img/legend/PoliceStation.png',
      highlight: false,
    },
    {
      name: 'Government Agency',
      showName: 'Government Agency',
      imgUrl: '/img/legend/GovernmentAgency.png',
      highlight: false,
    },
    {
      name: 'Camera Location',
      showName: 'Camera Location',
      imgUrl: '/img/legend/CameraLocation.png',
      highlight: false,
    },
    {
      name: 'Public Security Police Situation Point',
      showName: 'Public Security Police Situation Point',
      imgUrl: '/img/legend/PublicSecurityPolice.png',
      highlight: false,
    },
    {
      name: 'Alarm Event Point',
      showName: 'Alarm Event Point',
      imgUrl: '/img/legend/AlarmEventPoint.png',
      highlight: false,
    },
    {
      name: 'Historical Event Point',
      showName: 'Historical Event Point',
      imgUrl: '/img/legend/HistoricalEventPoint.png',
      highlight: false,
    },
    {
      name: 'Enterprise Location',
      showName: 'Enterprise Location',
      imgUrl: '/img/legend/EnterpriseLocation.png',
      highlight: false,
    },
  ],
}
